package ru.sber.bio4j.apigateway.user;

import static org.assertj.core.api.Assertions.assertThat;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.autoconfigure.data.r2dbc.DataR2dbcTest;
import org.springframework.r2dbc.core.DatabaseClient;
import org.springframework.test.context.ActiveProfiles;
import reactor.test.StepVerifier;

@DataR2dbcTest
@ActiveProfiles("test")
class GatewayUserRepositoryTest {

    @Autowired
    GatewayUserRepository repository;

    @Autowired
    DatabaseClient databaseClient;

    @BeforeEach
    void setUp() {
        databaseClient.sql("""
                CREATE TABLE IF NOT EXISTS gateway_users (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    login VARCHAR(128) NOT NULL UNIQUE,
                    active BOOLEAN NOT NULL DEFAULT TRUE,
                    roles VARCHAR(512) NOT NULL DEFAULT '',
                    user_grants VARCHAR(1024) NOT NULL DEFAULT ''
                )""").then().block();

        databaseClient.sql("DELETE FROM gateway_users").then().block();

        databaseClient.sql(
                "INSERT INTO gateway_users (login, active, roles, user_grants) VALUES ('active_user', TRUE, 'ROLE_USER,ROLE_ANALYST', 'grant.read,grant.export')"
        ).then().block();

        databaseClient.sql(
                "INSERT INTO gateway_users (login, active, roles, user_grants) VALUES ('inactive_user', FALSE, 'ROLE_USER', 'grant.read')"
        ).then().block();
    }

    @Test
    void shouldFindActiveUserByLogin() {
        StepVerifier.create(repository.findByLoginAndActiveTrue("active_user"))
                .assertNext(user -> {
                    assertThat(user.getLogin()).isEqualTo("active_user");
                    assertThat(user.getActive()).isTrue();
                    assertThat(user.getRoles()).isEqualTo("ROLE_USER,ROLE_ANALYST");
                    assertThat(user.getGrants()).isEqualTo("grant.read,grant.export");
                    assertThat(user.getId()).isNotNull();
                })
                .verifyComplete();
    }

    @Test
    void shouldReturnEmptyForInactiveUser() {
        StepVerifier.create(repository.findByLoginAndActiveTrue("inactive_user"))
                .verifyComplete();
    }

    @Test
    void shouldReturnEmptyForNonExistentLogin() {
        StepVerifier.create(repository.findByLoginAndActiveTrue("no_such_user"))
                .verifyComplete();
    }
}
